const dialectData = {
	"adverbs": ["Agilely",
		"Appropriately",
		"Assertively",
		"Authoritatively",
		"Collaboratively",
		"Compellingly",
		"Competently",
		"Completely",
		"Continually",
		"Conveniently",
		"Credibly",
		"Distinctively",
		"Dramatically",
		"Dynamically",
		"E-logistically",
		"Efficiently",
		"Effortfully",
		"Enthusiastically",
		"Escalatingly",
		"Fungibly",
		"Further",
		"Globally",
		"Going forward to",
		"Holistically",
		"Interactively",
		"Intrinsically",
		"Objectively",
		"Proactively",
		"Professionally",
		"Progressively",
		"Quickly",
		"Robustly",
		"Seamlessly",
		"Sequentially",
		"Synergistically",
		"Totally",
		"Transformatively",
		"Transversaly",
		"Uniquely",
		"Dauntlessly",
		"Inventorially"
	],
	"verbs": ["actualize",
		"administrate",
		"aggregate",
		"architect",
		"benchmark",
		"brand",
		"build",
		"capitalize",
		"cloudify",
		"communicate",
		"conceptualize",
		"constructivate",
		"coordinate",
		"create",
		"cultivate",
		"customize",
		"deliver",
		"deploy",
		"develop",
		"disintermediate",
		"disseminate",
		"drive",
		"e-enable",
		"embrace",
		"empower",
		"enable",
		"engage",
		"engage in synergy with",
		"engineer",
		"enhance",
		"envisioneer",
		"evisculate",
		"evolve",
		"expedite",
		"exploit",
		"extend",
		"fabricate",
		"facilitate",
		"fashion",
		"formulate",
		"foster",
		"generate",
		"getting the ball rolling for",
		"grow",
		"harness",
		"impact",
		"implement",
		"incentivize",
		"incept",
		"incubate",
		"initiate",
		"innovate",
		"integrate",
		"iterate",
		"leverage existing",
		"leverage other's",
		"maintain",
		"matrix",
		"maximize",
		"mesh",
		"monetize",
		"morph",
		"negotiate",
		"network",
		"onboard",
		"operationalize",
		"optimize",
		"orchestrate",
		"parallel task",
		"parallelize",
		"plagiarize",
		"plan",
		"pontificate",
		"predominate",
		"procrastinate",
		"productivate",
		"productize",
		"promote",
		"provide access to",
		"pursue",
		"re-engineer",
		"recapitualize",
		"reconceptualize",
		"redefine",
		"reintermediate",
		"reinvent",
		"releasing",
		"repurpose",
		"restore",
		"revolutionize",
		"right-shore",
		"scale",
		"seize",
		"sequence",
		"simplify",
		"strategize",
		"streamify",
		"streamline",
		"supply",
		"syndicate",
		"synergize",
		"synthesize",
		"target",
		"transform",
		"transition",
		"underwhelm",
		"unleash",
		"utilize",
		"visualize",
		"whiteboard",
		"congreet",
		"fractate",
		"budger",
		"fashionmonger",
		"hobnail",
		"hornbrook",
		"circle around to"
	],
	"verbs_with_ing": ["centering",
		"encapsulating",
		"envisioneering",
		"generating",
		"maturing",
		"maximizing",
		"mobilising",
		"redefining",
		"reinventing",
		"thrusting",
		"transforming",
		"transversing"
	],
	"whw_start": ["Imagining a world where we deliver",
		"Our goal is to stimulate",
		"Our strategy is to seize",
		"Our purpose is to add",
		"Our role is to",
		"We bring together",
		"We create",
		"We deliver",
		"We encourage",
		"We make",
		"We mediate",
		"We strive for",
		"We are passionate about",
		"We live to create",
		"We are making space for, and amplifying, and elevating"
	],
	"adjectives": ["2.0",
		"24/365",
		"24/7",
		"AI-powered",
		"B2B",
		"B2C",
		"RACI-reengineered",
		"accurate",
		"adaptive",
		"agile",
		"alternative",
		"an expanded array of",
		"backend",
		"backward-compatible",
		"baked-in",
		"best-of-breed",
		"bleeding-edge",
		"bottom-up",
		"bricks-and-clicks",
		"business",
		"business e-spansion-ready",
		"clicks-and-mortar",
		"client-based",
		"client-centered",
		"client-centric",
		"client-focused",
		"cloud-based",
		"cloud-centric",
		"cloud-ready",
		"cloudified",
		"collaborative",
		"compelling",
		"competitive",
		"cooperative",
		"corporate",
		"cost-effective",
		"covalent",
		"cross functional",
		"cross-functional",
		"cross-media",
		"cross-platform",
		"cross-unit",
		"customer directed",
		"customized",
		"cutting-edge",
		"disambiguated",
		"distinctive",
		"distributed",
		"diverse",
		"dynamic",
		"e-business",
		"economically sound",
		"effective",
		"efficient",
		"elastic",
		"embedded",
		"emerging",
		"empowered",
		"enabled",
		"end-to-end",
		"enterprise",
		"enterprise-wide",
		"equity invested",
		"error-free",
		"escalated",
		"ethical",
		"excellent",
		"exceptional",
		"executive committee level",
		"extensible",
		"extensive",
		"face-to-face",
		"flexible",
		"focused",
		"focused investments towards",
		"frictionless",
		"front-end",
		"fully researched",
		"fully tested",
		"functional",
		"functionalized",
		"fungible",
		"future-proof",
		"global",
		"go-forward",
		"'go-to'",
		"goal-oriented",
		"granular",
		"high standards in",
		"high-payoff",
		"high-quality",
		"highly efficient",
		"holistic",
		"hyper-scale",
		"impactful",
		"imputed",
		"inexpensive",
		"innovative",
		"installed base",
		"integrated",
		"interactive",
		"interdependent",
		"interoperable",
		"intuitive",
		"just-in-time",
		"leading-edge",
		"leveraged",
		"long-term high-impact",
		"low-risk high-yield",
		"maintainable",
		"market positioning",
		"market-driven",
		"mission-critical",
		"mobile-first",
		"multidisciplinary",
		"multifunctional",
		"multimedia based",
		"networked",
		"next-generation",
		"omnichanneled",
		"on-demand",
		"one-to-one",
		"open-source",
		"optimal",
		"orthogonal",
		"out-of-the-box",
		"pandemic",
		"parallel",
		"people-centric",
		"performance-based",
		"plug-and-play",
		"premier",
		"premium",
		"principle-centered",
		"proactive",
		"process-centric",
		"professional",
		"progressive",
		"prospective",
		"quality",
		"real-time",
		"reliable",
		"reprofiled",
		"resource-leveling",
		"resource-maximizing",
		"resource-sucking",
		"revolutionary",
		"robust",
		"scalable",
		"seamless",
		"silo-busting",
		"socially-responsible",
		"stand-alone",
		"standardized",
		"standards-compliant",
		"state of the art",
		"sticky",
		"strategic",
		"superior",
		"sustainable",
		"synergistic",
		"system business e-spansion-ready",
		"system-level",
		"systemwide",
		"tactical",
		"team-building",
		"team-driven",
		"technically sound",
		"timely",
		"top-line",
		"transparent",
		"turnkey",
		"ubiquitous",
		"unique",
		"user-centric",
		"user-friendly",
		"user-friendly",
		"value-added",
		"value-based",
		"vertical",
		"viral",
		"virtual",
		"visionary",
		"web-enabled",
		"wireless",
		"world-class",
		"worldwide",
		"zero-to-hero",
		"imploratory",
		"lustrous",
		"skimble-skamble",
		"spleenful",
		"unbosomed",
		"tortive",
		"multifaceted",
		"online",
		"secure",
		"crucial",
		"data-driven",
		"data-focused",
		"circling back"
	],
	"nouns": ["ROI",
		"USPs",
		"UX",
		"action items",
		"adoption",
		"advanced analytics",
		"alignments",
		"applications",
		"approaches",
		"architectures",
		"autonomous ergonomics",
		"bandwidth",
		"benefits",
		"best practices",
		"bottom line",
		"capability building",
		"catalysts for change",
		"causalities",
		"channels",
		"cloud functionality",
		"clouds",
		"collaboration and idea-sharing",
		"communities",
		"communities of practice",
		"consumer empowerment",
		"content",
		"convergence",
		"core competencies",
		"corporate buy-in",
		"critical success factors",
		"customer service",
		"data",
		"deep learning",
		"deliverables",
		"delivery models",
		"'doing good while doing well' ethos",
		"e-business",
		"e-commerce",
		"e-markets",
		"e-services",
		"e-tailers",
		"enterprise architecture",
		"experiences",
		"expertise",
		"frameworks",
		"functionalities",
		"fungibility",
		"growth drivers",
		"growth strategies",
		"human capital",
		"ideas",
		"imperatives",
		"infomediaries",
		"information",
		"infrastructures",
		"initiatives",
		"innovation",
		"intellectual capital",
		"interfaces",
		"internal or 'organic' sources",
		"key audience segments",
		"key performance indicators",
		"leadership",
		"leadership skills",
		"'remote leadership'",
		"Diverse Remote Teams",
		"logistics",
		"manufactured products",
		"markets",
		"materials",
		"meta-services",
		"methodologies",
		"methods of empowerment",
		"metrics",
		"mindshare",
		"models",
		"networks",
		"niche markets",
		"niches",
		"opportunities",
		"organisational culture",
		"'out of the box' thinking",
		"outsourcing",
		"paradigms",
		"partnerships",
		"platforms",
		"portals",
		"potentialities",
		"process improvements",
		"processes",
		"products",
		"quality vectors",
		"reinforcement learning",
		"relationships",
		"resources",
		"responsibility assignment matrices (RAMS)",
		"results",
		"scenarios",
		"schemas",
		"scrum masters",
		"scrums",
		"service reprofiling",
		"services",
		"solutions",
		"sources",
		"sprints",
		"standard operating procedures",
		"storage",
		"strategic imperatives",
		"strategic theme areas",
		"supply chains",
		"survival strategies for the next 5 years",
		"synergy",
		"systems",
		"talent release",
		"technologies",
		"technology",
		"testing procedures",
		"total linkage",
		"transformation",
		"transversalities",
		"users",
		"value",
		"value proposition",
		"vertically aligned portals",
		"virtualization",
		"web services",
		"web-readiness",
		"wins",
		"oppugnancy",
		"machine learning",
		"'Voice of customer'",
		"design options",
		"grocery penetration",
		"deep dive",
		"business success",
		"market drivers",
		"conversion and storytelling",
		"future-critical markets",
		"AI applications portfolios",
		"blockchain enablement",
		"blockchains",
		"real impact",
		"agile pivoting",
		"root-cause analyses",
		"end-to-end solutions",
		"end-to-end workflows",
		"Objectives and Key Results (OKRs)",
		"further strides",
		"'putting our people at the centre of everything we do'",
		"installed base selling",
		"aftersales success",
		"Adaptive and Agile business",
		"ambition statements",
		"value statements",
		"stakeholder decision making",
		"omnichannel savviness",
		"working up to a 'hard stop' at 3pm",
		"level-set expectations",
		"double-digit growth",
		"embedded strategic advantage",
		"topline sales",
		"campaign formats",
		"digital business transformation (DBT)"
	],
	"links": ["after",
		"and",
		"and reaching out with",
		"channelled with",
		"co-created with",
		"(enabling System A to talk to System B) through",
		"following",
		"for",
		"from",
		"going head for head with",
		"in addition to",
		"on top of",
		"rather than",
		"(shaping how we are today) with",
		"through",
		"towards",
		"tunnelled through",
		"using best efforts to achieve",
		"via",
		"whilst maintaining",
		"with",
		"without",
		"going forward to",
		"holistically leading towards",
		"with openness to change to",
		"honestly brokering through"
	],
	"_ALEadverbs": ["Agilely",
		"Unprecedently",
		"Bravely",
		"Hoppingly",
		"Yeastily",
		"Effortfully",
		"Enthusiastically",
		"Progressively",
		"Robustly",
		"Seamlessly",
		"Whilst following the latest craft ale trends",
		"Froth-blowingly"
	],
	"_ALEverbs": ["architect",
		"build",
		"create",
		"cultivate",
		"customize",
		"embrace",
		"enable",
		"engage",
		"enhance",
		"extend",
		"fashion",
		"maximize",
		"network",
		"plan",
		"revolutionize",
		"seize",
		"brew",
		"mash",
		"hop",
		"pour",
		"cask",
		"chill",
		"serve",
		"invite",
		"drink"
	],
	"_ALEverbs_with_ing": ["bubbling",
		"entertaining",
		"enjoying",
		"drinking",
		"serving",
		"imbibing",
		"cask tapping"
	],
	"_ALEadjectives": ["night time",
		"chilled",
		"cosy",
		"memorable",
		"late night",
		"hoppy",
		"malty",
		"wild",
		"special",
		"unique",
		"bespoke",
		"not-well-known",
		"tapped",
		"casked",
		"mixed",
		"bitter",
		"conditioned",
		"bottled",
		"multi-hopped",
		"uniquely malted",
		"brewhouse-level",
		"drinker-friendly",
		"high-quality",
		"centrifuged",
		"just-in-time",
		"at the pump",
		"state of the art",
		"consistent",
		"a great range of",
		"cellared",
		"beer-tented",
		"brewery-toured",
		"Oktoberfested",
		"brewhouse engineered",
		"laboratory controlled"
	],
	"_ALEnouns": ["pints",
		"night time outings",
		"tastings",
		"quick halves",
		"chasers",
		"food & drink",
		"bars",
		"clubs",
		"secret venues",
		"lock-ins",
		"private drinking",
		"special beer tables",
		"casks",
		"malt knowledge",
		"end-to-end brewing processes",
		"21st century brewing",
		"malting approaches",
		"hop additions",
		"alcohol outputs",
		"sacchyrometer readings",
		"original gravities",
		"liquoring back techniques",
		"hot caustic washes",
		"pitching of yeast",
		"product focus",
		"brewers wellies",
		"pump management",
		"keezers",
		"shives",
		"keystones",
		"strike temperatures",
		"beer engines",
		"improved stacking of 'nonic' pint glasses",
		"hop-informed bar stewards",
		"malt-loving bar stewards",
		"malted wheat usage",
		"bags of melanoidin",
		"lactate additions",
		"isinglass dilution"
	],
	"_ALElinks": ["partying-on to",
		"tasting with",
		"randomly finding",
		"adding salty snacks to",
		"spitting on the sawdust with",
		"boosting the OG by",
		"improving the taste of",
		"achieving 'chill' haze through",
		"(racked on the bar) because of"
	],
	"_ALEtags": ["#craftale",
		"#microbrewery",
		"#beer🍺",
		"#cheers",
		"#ales🍻",
		"#caskale",
		"#hoptastic",
		"#specialbrew",
		"#mashingtonight",
		"#ontap",
		"#guestales"
	],
	"_BREXITEERadverbs": ["Enthusiastically",
		"Proactively",
		"Independently",
		"Robustly",
		"Seamlessly",
		"Transformatively",
		"Thrustingly",
		"Patriotically",
		"Oven-readily",
		"Greatly",
		"Sun-lit pasture chasingly",
		"Eurosceptically",
		"Outscoldingly",
		"Termagantly",
		"Discombobulatingly",
		"Compellingly",
		"Specifically - and in a limited way - ",
		"Bloviatingly",
		"Shape-shiftingly",
		"Imposingly",
		"Prospering mightily",
		"Bigly"
	],
	"_BREXITEERverbs_with_ing": ["free-ing",
		"Great Britainly leading",
		"unleashing",
		"castigating",
		"oppignorating",
		"border-controlling"
	],
	"_BREXITEERadjectives": ["UK-centric",
		"nook-shotten",
		"fudged",
		"silent-majority-inspired",
		"red-tape-snipping",
		"EU-ready",
		"well-thought-out",
		"post-Brexit advantaged"
	],
	"_BREXITEERnouns": ["21st century global trade",
		"Great GB approaches",
		"big British data outputs",
		"British guile",
		"independence and fortune-sharing",
		"Royal approval",
		"trade delivery models",
		"'Antipodean farm to British table' time",
		"free ports",
		"wealth gap closure",
		"immigration workforce resilience",
		"inward investments",
		"key excellence indicators",
		"global mastery",
		"freedom-fighting culture",
		"export productivity",
		"patent care",
		"international focus",
		"British safety",
		"democratically-reported outcomes",
		"paid-for performance value",
		"voter approval",
		"population wealth",
		"referendum reporting",
		"global outlook reprofiling",
		"'honoring the referendum' delivery teams",
		"export throughput",
		"import procurement",
		"Team GB transformation",
		"revokement",
		"sotissiers",
		"enjambment",
		"factotums",
		"gimcracks",
		"monstrous imposition",
		"sententious guff",
		"'getting Brexit done'",
		"diminishing of the Islington remainer elite",
		"border control models",
		"fish pillaging",
		"tariff arbitrage",
		"freeports",
		"sovereign equals",
		"activist lawyers",
		"lorry parks",
		"'Brexit negotiation blame games'",
		"smearing of 'grubby directors of immigration solicitor companies'",
		"opposition of things we never fought for in WWII",
		"'cod wars'",
		"breaking of international law 'in a very specific and limited way'",
		"'truth twisters'",
		"prorogations",
		"delivery of an Internal Market Bill",
		"trips to Perugia",
		"'festival of Brexit', plans",
		"Kent lorry parks",
		"opportunities for Remainers to have a go at Brexit",
		"rebranding of 'no deal' as an 'Australian deal'",
		"canary traps",
		"veritable geysers of confected indignation",
		"post-Brexit travel rules",
		"accelerated approval of vaccines",
		"sovereign control of borders",
		"Northern Ireland protocols",
		"£840 rolls of wallpaper",
		"sausage exports",
		"triggering of the Downstream Oil Protocol",
		"use of prisoners to process meat",
		"sewage alerts",
		"removal of GB car stickers",
		"lorry tailbacks for customs declarations",
		"pyramids of piffle",
		"glittering generalities",
		"implementation of Sanitary and Phytosanitary (SPS) checks",
		"levelling-up",
		"'Hasta la vista!'s",
		"tackling of 'anti-growth coalitions'",
		"leadership campaigns",
		"Trussonomics",
		"challenges of Treasury orthodoxy"
	],
	"_BREXITEERlinks": ["forced upon",
		"controlled through",
		"secretly influenced by",
		"through a hidden agenda of",
		"liberated by",
		"escaping the EU by",
		"avoiding the clutches through",
		"besmirched with",
		"<i>ecce signum</i>",
		"(redacted from the Russia report) because of",
		"blaming Europe for",
		"taking personal charge for",
		"having a moral duty to",
		"with a 'convivial and fraternal spirit' to",
		"<i>res ipsa loquitur</i>",
		"mini-budgeted for"
	],
	"_BREXITEERtags": ["#Brexit",
		"#BrexitBritain",
		"#postBrexit",
		"#sunlituplands",
		"#globalBritain"
	],
	"_CONadverbs": ["Frighteningly",
		"Secretly",
		"Purposefully",
		"Scaringly",
		"Unbelievably",
		"In-plain-sight",
		"Knowingly",
		"Controllingly",
		"Jet streamly",
		"Compellingly",
		"Area 51-like",
		"Through a spirit of deceit",
		"Imposingly"
	],
	"_CONnouns": ["vaccination of vulnerable groups",
		"atmospheric gas distribution by jet streams",
		"Bill Gates implants",
		"tin foil hats",
		"alien abductions",
		"UFO sightings",
		"disappearances",
		"mind controls",
		"5G networks",
		"tape and scrape cleansers",
		"hidden agendas",
		"left wing conspiracies",
		"right wing ideology",
		"wiping out of history",
		"disruption of law and order",
		"removal of statues",
		"sleeper cells",
		"broken encryption",
		"societal breakdown",
		"additives to the water",
		"fogging of consciousness",
		"unknown players",
		"elitist purpose",
		"unexplained deaths",
		"remote vehicle controls",
		"loss of free will",
		"billionaires",
		"controls of main stream media",
		"designed purpose",
		"chemtrails",
		"Secret Large-scale Atmospheric Programs",
		"New World order",
		"illuminati",
		"animal spies",
		"Deep State planning",
		"implementation of \"The Plan\"",
		"Flat Earth beliefs",
		"lower classes working to overturn the social order",
		"brainwashed herds",
		"fusion paranoia",
		"woke elite",
		"COVID plandemic delivery",
		"pro-muzzle propagandists",
		"redacted Russia reports",
		"underestimated Russian threats",
		"underestimated Chinese threats",
		"NHS privatisation",
		"financially-backed lobby groups",
		"immigrants crossing the channel",
		"understanding that war is peace",
		"knowing that freedom is slavery",
		"sharing that ignorance is strength",
		"POTUS distractions by being COVID positive",
		"Western-backed neoliberal coup attempts",
		"anti-Soviet \"Chain of Freedom\" stunts",
		"astroturfed ops",
		"linking our biodata to cryptocurrency",
		"nano crystalline particles (mini antennae) in vaccines storing information in the cloud",
		"introductions of cymers (non-human DNA) via vaccinations",
		"metal particles in vaccines that turn into 5g transmitters",
		"shutting down the entire Twitter network to prevent spread of negative news",
		"dismantling of white supremacy",
		"Stopping the Steal",
		"baseless claims of voter fraud",
		"achieving the 'Great Reset'",
		"mass extermination of humanity",
		"impositions from Globalists",
		"Globalists' client states",
		"acts of sedition",
		"Calling in the Legislature under Article II, Section 1, Clause 2"
	],
	"_CONlinks": ["forced upon",
		"controlled through",
		"secretly influenced by",
		"through a hidden agenda of",
		"manipulated through",
		"covertly influenced by"
	],
	"_CONtags": ["#ConspiracyTheory",
		"#conspiracy",
		"#secrets",
		"#notcrazy",
		"#deepstate",
		"#undercover"
	],
	"_COVIDadverbs": ["Agilely",
		"Unprecedently",
		"Compassionately",
		"Diversely",
		"Efficiently",
		"Effortfully",
		"Enthusiastically",
		"Holistically",
		"Interactively",
		"Proactively",
		"Swabbingly",
		"Progressively",
		"Robustly",
		"Seamlessly",
		"Whilst following the science",
		"Transformatively",
		"Curve flatteningly",
		"Rolling averagingly",
		"Pandemic zeitgeistly",
		"Virally",
		"Self-isolatingly",
		"Tier escalatingly"
	],
	"_COVIDverbs_with_ing": ["bedabbling",
		"COVID-19 mitigating",
		"ICU capacity-sparing"
	],
	"_COVIDadjectives": ["COVID-secure",
		"sterilised",
		"socially-distanced",
		"a coronacoaster of a",
		"self-isolated",
		"PCR-tested",
		"fully-PPE'd",
		"aerosol generated",
		"COVID risk-assessed"
	],
	"_COVIDnouns": ["track and trace service",
		"tracking apps",
		"COVID testing frameworks",
		"PPE delivery chains",
		"filtering facemasks",
		"FFP3 excellence",
		"social distancing",
		"flattening the curve",
		"excess mortality reduction",
		"shielded group performance",
		"public health workforce resilience",
		"lockdown precautions",
		"pandemic planning",
		"PCR screening",
		"SARS-CoV-2 testing brilliance",
		"pathology productivity",
		"patient ventilator care",
		"ARDS detection",
		"economic mitigation",
		"SARS-related outcomes",
		"healthcare system preparedness",
		"antibody testing",
		"herd immunity",
		"trace and isolate ideology",
		"COVID symptom tracker",
		"persistent cough detection",
		"risk profiling",
		"PPE procurement",
		"COVID-ready transformation",
		"self-isolation",
		"COVID new normal",
		"hypoxia mitigation strategy",
		"community-acquired pneumonia protocols",
		"COVID 'lock and load' service delivery",
		"AGP safety",
		"Aerosol-Generating Procedures",
		"Wuhan-level readiness",
		"COVID cluster-busting",
		"coronacoasteering",
		"coronaconventions",
		"resilient post-pandemic new reality",
		"flip-flops on Bournemouth beach",
		"second wave prevention",
		"COVID-19 death rate reduction",
		"Pandemic Leave Disaster Payments",
		"Eat Out to Help Out schemes",
		"COVID-secure fallow periods",
		"COVID-secure school openings",
		"'tier 4 school closures'",
		"social bubble controls",
		"delivery of the fizz and excitement you get in a good workplace",
		"national effort against coronavirus",
		"extra new innovative tests",
		"'rules of 6'",
		"10pm curfews",
		"promotion of 'hands, face, space'",
		"shielded vulnerables",
		"'tier 3' local lockdowns",
		"'walk on the left' in corridors instructions",
		"bubbling up of households",
		"'pulling up the drawbridge' on Northern towns",
		"failures of Test and Trace",
		"Government COVID scenario plans B and C",
		"'tier 2' transitions",
		"battling with anti-vaccination propaganda",
		"real-time tracking of mobile phone location to enforce lockdowns",
		"vaccine efficacy results",
		"T-cell immunity",
		"lateral flow (immunochromatographic assay) tests",
		"spreading of COVID in supermarkets",
		"COVID vaccination programmes",
		"SARS-CoV-2 antigen tests",
		"Tier 2 Substantial Meals (with Scotch Egg)",
		"vaccination celebrations",
		"UK Variant B.1.1.7 resiliance",
		"Pfizer-BioNTech vaccine delivery",
		"mass vaccination programmes",
		"third lockdown success",
		"Tier 4 (stay at home) orders",
		"school openings (and closings)",
		"High-Flow Nasal Oxygen (HFNO) delivery",
		"oxygen supplies",
		"India variant B.1.617",
		"'variants under investigation'",
		"\"bodies piled high in the thousands\"",
		"'doing a Brownlow' (winning of lucrative public contracts)",
		"surge testing",
		"surge vaccinations",
		"tackling of variant hotspot areas",
		"panic buying",
		"sticking with Plan 'A'",
		"sustainable pressures",
		"delta plus variant",
		"variant AY4.2",
		"omicron variant B.1.1.529",
		"HEPA filters",
		"CO2 monitors",
		"bring your own booze parties",
		"No. 10 'office' parties"
	],
	"_COVIDlinks": ["following the science to achieve",
		"flattening the curve of",
		"bedabbled through",
		"opening up the economy with",
		"achieving the 'new normal' through"
	],
	"_COVIDtags": ["#coronavirus",
		"#COVID19",
		"#Covid_19",
		"#COVID-19"
	],
	"_EDadverbs": ["Agilely",
		"Behaviourally",
		"Diversely",
		"Educationally",
		"Effortfully",
		"Enthusiastically",
		"Holistically",
		"Instructively",
		"Interactively",
		"Pedagogically",
		"Proactively",
		"Professionally",
		"Professorially",
		"Progressively",
		"Purposefully",
		"Robustly",
		"Seamlessly",
		"Socially constructivistly",
		"Transformatively"
	],
	"_EDnouns": ["Learning 2.0",
		"SCORM units",
		"adaptive learning",
		"behaviour change",
		"blended learning",
		"competencies",
		"curriculum development",
		"deep learning",
		"e-learning",
		"educational evaluation",
		"instructional design",
		"instructional workshops",
		"intended learning outcomes",
		"learner assessments",
		"learner outcomes measures",
		"learner profiling",
		"learner-centricity",
		"learning needs",
		"learning objectives",
		"learning platforms",
		"objective summative assessment",
		"participant performance",
		"predictive testing",
		"rote learning",
		"situated cognition",
		"student conditioning",
		"teachable moments",
		"teaching faculty fame",
		"teaching precision",
		"teaching success",
		"textbook instruction",
		"triangulated learning gaps",
		"machine learning",
		"'outcomes-based planning'",
		"omnichannel savviness"
	],
	"_EDtags": ["#Learning",
		"#training",
		"#development",
		"#edtech"
	],
	"_ENTadverbs": ["Passionately",
		"Unbelievably",
		"Agreeably",
		"Lovingly",
		"Tenderly",
		"Enthusiastically",
		"Distinctively",
		"Nocturnally",
		"Seamlessly",
		"Freely",
		"With a spirit of adventure"
	],
	"_ENTverbs": ["architect",
		"build",
		"capitalize",
		"coordinate",
		"create",
		"cultivate",
		"customize",
		"embrace",
		"enable",
		"engage",
		"enhance",
		"extend",
		"fashion",
		"maximize",
		"network",
		"plan",
		"revolutionize",
		"seize"
	],
	"_ENTverbs_with_ing": ["bubbling",
		"entertaining",
		"enjoying"
	],
	"_ENTadjectives": ["night time",
		"chilled",
		"cosy",
		"memorable",
		"late night",
		"quiet",
		"thrilling",
		"wild",
		"special",
		"unique",
		"bespoke",
		"not-well-known"
	],
	"_ENTnouns": ["cocktails",
		"night time outings",
		"beautiful nights out",
		"watching of the city lights",
		"drinks",
		"food & drink",
		"bars",
		"clubs",
		"secret venues",
		"lock-ins",
		"private dining",
		"special tables",
		"dances"
	],
	"_ENTlinks": ["partying-on to",
		"chilling out with",
		"randomly finding"
	],
	"_ENTtags": ["#citylife",
		"#nightout",
		"#london",
		"#londonclubbing",
		"#londonforever",
		"#londonisopen",
		"#londonnightout",
		"#londonnightlife",
		"#londonnights",
		"#LondonSpirit",
		"#nightlife",
		"#londoncity",
		"#londonlife",
		"#london🇬🇧",
		"#londonlove",
		"#londonbylondoners",
		"#londonfoodies",
		"#london4all",
		"#londonguru",
		"#londonvibes"
	],
	"_GREENadverbs": ["Passionately",
		"Unbelievably",
		"Renewably",
		"Lovingly",
		"Responsibly",
		"Enthusiastically",
		"Distinctively",
		"Bravely",
		"Equitably",
		"Compassionately",
		"Compellingly",
		"Whilst protecting what we have"
	],
	"_GREENverbs_with_ing": ["planet-sparing",
		"electrifying",
		"powering",
		"driving",
		"storing",
		"generating",
		"sharing"
	],
	"_GREENadjectives": ["wild",
		"protected",
		"sustainable",
		"special",
		"unique",
		"renewable"
	],
	"_GREENnouns": ["wind turbines",
		"solar installations",
		"reductions of carbon foot prints",
		"net-zero targets",
		"carbon taxation policies",
		"insulation promises",
		"commitments to reduce fossil fuels",
		"2050 targets",
		"2070 targets",
		"carbon capture technologies",
		"political lock-ins",
		"prevention of mass migrations",
		"special energies",
		"environmental protections",
		"forming of Greenscamming entities",
		"promotion of 'clean burning natural gas'",
		"clear skies initiatives",
		"'defeat devices'",
		"lobbying for 'clean coal'",
		"'go green' initiatives",
		"drop-in bioplastics"
	],
	"_GREENlinks": ["delivering on corporate responsibility to achieve",
		"driving forward with innovation for",
		"finding futures we can be proud of by",
		"achieving our purpose through",
		"sharing what we love by",
		"caring for each other by",
		"nurturing our environment with"
	],
	"_GREENtags": ["#green",
		"#renewables",
		"#globalwarming",
		"#carboncapture",
		"#cop26",
		"#parisagreement",
		"#welovegreta"
	],
	"_LEGALadverbs": ["Assertively",
		"Authoritatively",
		"Compellingly",
		"Robustly",
		"Seamlessly",
		"Transformatively",
		"Thrustingly",
		"Dynamically",
		"Effortfully",
		"Engagingly",
		"Enthusiastically",
		"Proactively",
		"Purposefully",
		"In a reasonably foreseeable way",
		"Adversarially",
		"Aiding and abettingly",
		"Annuitantly",
		"Antenuptually",
		"In a binding precedent",
		"In the manner of a Cartel",
		"Jointly and severally",
		"Preferentially",
		"By teeming and lading"
	],
	"_LEGALverbs_with_ing": ["transacting 'at arms length'",
		"conveyancing",
		"Copyrighting"
	],
	"_LEGALadjectives": ["multi-specialist",
		"legally sure-footed",
		"assured",
		"attested",
		"audited",
		"bare-trusteed",
		"bench-warranted",
		"bequethed",
		"compensated",
		"contracted",
		"foreclosed",
		"indicted",
		"intimidated",
		"misconducted",
		"misrepresented",
		"naturalised",
		"novated",
		"timeshared",
		"transferable",
		"wayleaved"
	],
	"_LEGALnouns": ["judgements",
		"court orders",
		"legal positions",
		"Ancillary relief",
		"Mareva Injunctions",
		"Anton Pillar Orders",
		"Calderbank Offers",
		"equitable interests",
		"causations at law",
		"causations in fact",
		"statutory instruments",
		"law and order",
		"seamless briefs",
		"Blue Pencil Rules",
		"restraints of trade",
		"quoting of the <i>Bushell v Faith</i> clause",
		"notaries public",
		"tenants in common",
		"citings of the man on the Clapham omnibus",
		"integrated legal support",
		"handling of salmon in suspicious circumstances (1986 poaching laws)",
		"malicious communications",
		"abatements",
		"abuses of process",
		"acquittals",
		"Acts of God",
		"delivery for you and all your successors in title hereinafter",
		"adjudication orders",
		"affadavits",
		"ambulatory wills",
		"arbitrage",
		"chattels personal",
		"deployments of a codifying statute",
		"contemptuous damages",
		"exemplary damages",
		"interlocutory proceedings",
		"malicious falsehoods",
		"muniments",
		"possessory titles",
		"promissary notes",
		"just and equitable recognisance",
		"vexatious litigants",
		"overage clauses",
		"deeds of access"
	],
	"_LEGALlinks": ["<i>ipso facto</i>",
		"<i>uberrimae fidei</i>",
		"<i>a priori</i>",
		"<i>non sequitor</i>",
		"<i>nemo dat non quod habet</i>",
		"<i>plene administravit</i>",
		"<i>ab initio</i>",
		"with respect to the aforementioned",
		"hitherto",
		"adjourned <i>sine die</i>",
		"<i>ad valorum</i>",
		"<i>bona vacantia</i>",
		"<i>et seq</i>",
		"<i>res ipsa loquitur</i>"
	],
	"_LEGALtags": ["#legal",
		"#legalese",
		"#legallexicon"
	],
	"_NHSadverbs": ["Agilely",
		"Carefully",
		"Compassionately",
		"Diversely",
		"Efficiently",
		"Effortfully",
		"Enthusiastically",
		"Holistically",
		"Interactively",
		"Proactively",
		"Professionally",
		"Progressively",
		"Robustly",
		"Seamlessly",
		"Transformatively",
		"Positively",
		"Enablingly",
		"Harnessingly"
	],
	"_NHSnouns": ["21st century hospital care",
		"approaches",
		"big health data outputs",
		"clinical guidelines",
		"collaboration and idea-sharing",
		"commissioner approval",
		"delivery models",
		"door to needle time",
		"frameworks",
		"health gap closure",
		"hospital workforce resilience",
		"inward investments",
		"key performance indicators",
		"medical mastery",
		"organisational culture",
		"pathology productivity",
		"patient care",
		"patient focus",
		"patient safety",
		"patient-reported outcomes",
		"'pay for performance' value",
		"payer approval",
		"population health",
		"radiology reporting",
		"service reprofiling",
		"surgical scrub teams",
		"surgical throughput",
		"therapy procurement",
		"transformation",
		"bio-revolution",
		"'listening exercises'",
		"person-centered care",
		"'vision papers'",
		"'periods of consolidation'",
		"'demand management strategies'",
		"agile pivoting",
		"end-to-end clinical processes",
		"auditable mandatory trainings",
		"sterile techniques",
		"drug delivery methodologies",
		"medically optimised discharges",
		"ambition statements",
		"in-vitro Bioequivalence Results",
		"anomalous health incidents (Havana Syndrome)",
		"sustaintable healthsystem pressures",
		"stopping of Oxford commas",
		"avoidance of overwhelmingly negative narratives",
		"clinical networks",
		"whole system improvements",
		"engines for change",
		"clinical leadership",
		"networks influence commissioning",
		"'care and services that we and our families would want to use'",
		"'enabling people to live healthier lives'",
		"'enabling people to live more independent lives'",
		"high-quality seamless care"
	],
	"_NHStags": ["#healthcare",
		"#NHS",
		"#hospital",
		"#medical"
	],
	"_PUBadverbs": ["Agilely",
		"Authoritatively",
		"Compellingly",
		"Credibly",
		"Distinctively",
		"Editorially",
		"Effortfully",
		"For the published record",
		"Globally",
		"Interactively",
		"Robustly",
		"Scientifically"
	],
	"_PUBnouns": ["UX",
		"above the fold content",
		"abstracts",
		"advertising channels",
		"citation index",
		"click bait",
		"cloud content consumption",
		"congress exposure",
		"consumer and reader empowerment",
		"documented artefacts",
		"e-journals",
		"hypertext",
		"impressions",
		"industry reprints",
		"journals",
		"key audience segments",
		"omnichannel delivery",
		"paper alternatives",
		"publications",
		"publishing excellence",
		"purposeful delivery",
		"readership value metrics",
		"robust journalism",
		"routes to mobile markets",
		"scientific endeavour",
		"machine learning",
		"digital object identifiers",
		"'hacked materials policies'",
		"automated performance technology for publishers",
		"voice-interactive-storytelling",
		"embedding technology in publishing",
		"print on demand technologies",
		"omnichannel savviness"
	],
	"_PUBtags": ["#publishing",
		"#digitalmedia"
	],
	"_STEMadverbs": ["Compellingly",
		"Dynamically",
		"Effortfully",
		"Engagingly",
		"Enthusiastically",
		"Proactively",
		"Purposefully",
		"Robustly",
		"Seamlessly",
		"Using pencil and paper",
		"Calculatingly",
		"Orthogonally",
		"Professorially",
		"Using a compass and ruler",
		"Using logarithm tables"
	],
	"_STEMnouns": ["statistically-significant results",
		"Bayesian hypotheses",
		"paradigm shifts",
		"Newtons per metre",
		"constructions",
		"differential calculus",
		"squaring of the circle",
		"novel results",
		"Nobel laureates",
		"big science investments",
		"scientific endeavours",
		"adsorptions",
		"alternative hypotheses",
		"critical mass",
		"DevOps",
		"frameworks",
		"folksonomies",
		"cyber-physical systems",
		"data mining",
		"disruptive technologies",
		"ideation management",
		"quantum supremacy",
		"nanotechnology",
		"skeumorphic entities",
		"systems development life cycles",
		"toolchains",
		"vortals",
		"atomic orbitals",
		"Spache Readability Scores",
		"frictionless software development",
		"ephemeral user content",
		"internet of things",
		"Lambda",
		"software-defined networking",
		"Faraday cages",
		"supermagnets",
		"light-emitting diodes",
		"superfluxed hinged robotics",
		"Bose-Einstein condensates",
		"twin wall technologies",
		"flat slab constructions",
		"3D volumetric modules",
		"biomass energy production",
		"hydrogen fuel cells",
		"silicon anode lithium-ion batteries",
		"Lithium-sulphur batteries",
		"parallel AC converters",
		"nuclear fusion capability",
		"plasma clouds",
		"lithium mines",
		"cybersecurity strategies",
		"SaaS",
		"'electrified small-format mobility' (electric bikes)",
		"quantum technology programmes",
		"cloud video editing",
		"voice technologies",
		"pavement technology",
		"Actuator Geometry Optimisation",
		"in-vitro Bioequivalence Results"
	],
	"_STEMlinks": ["integrated through",
		"constructed by",
		"through a reductivist agenda of",
		"<i>Q.E.D.</i>",
		"disrupted by",
		"digitally remastered with",
		"through convergence with",
		"benchmarked by",
		"in a mashup with",
		"with datafication of"
	],
	"_STEMtags": ["#STEM",
		"#science",
		"#technology"
	],
	"_VSadverbs": ["Affirmatively",
		"Compassionately",
		"Compellingly",
		"Communally",
		"Diversely",
		"Dynamically",
		"Effortfully",
		"Engagingly",
		"Enthusiastically",
		"Holistically",
		"Proactively",
		"Purposefully",
		"Robustly",
		"Seamlessly",
		"Socially consciously",
		"Through a spirit of giving",
		"Voluntarily"
	],
	"_VSnouns": ["approaches",
		"collaboration and idea-sharing",
		"co-creations",
		"community needs",
		"cooperation",
		"generosity",
		"donations",
		"enduring purpose",
		"frameworks",
		"fulfilling outcomes",
		"giving",
		"group actions",
		"healing",
		"organisational culture",
		"rewards",
		"social cohesion",
		"sustainability",
		"time-giving",
		"transformation",
		"unmet needs",
		"volunteer fulfillment",
		"non-profit endeavours",
		"generosity",
		"holistic approaches",
		"kerbside fiscal improvements",
		"corporate responsibility"
	],
	"_VStags": ["#Volunteering",
		"#volunteers"
	],
	"appraise_starts": ["Achieves optimal levels of performance and accomplishment with",
		"Achieves optimal levels of performance and accomplishment for",
		"Provides strong evidence of",
		"Excels at developing programs / strategies that have delivered",
		"Continuously examines administrative effectiveness and seeks better procedures such as",
		"Develops successful administrative strategies such as",
		"Establishes effective systems for information retrieval through",
		"Improves administrative support systems through",
		"Keeps documents organized via",
		"Keeps emails organized in",
		"Shows a sincere interest in",
		"Shows sincere interest in solutions to problems in",
		"Demonstrates a mindset of being solutions-focussed in",
		"Lends support and guidance to others by",
		"Uses sound coaching techniques to solve disciplinary problems in",
		"Provides continuous coaching in",
		"Is highly respected by others for sharing concerns, problems, and opportunities in",
		"Effectively communicates expectations in",
		"Excels in facilitating group discussions in",
		"Keeps meetings action-oriented by task in",
		"Effectively communicates upward, downward, and laterally in",
		"Enforces our policies and values without creating negative reactions in",
		"Encourages collaboration with the team in",
		"Shares ideas and techniques in",
		"Builds strong relationships with others by",
		"Displays a harmonious and cooperative spirit by",
		"Gladly shares expertise in",
		"Seeks creative alternatives such as",
		"Clever and imaginative when confronted with obstacles in",
		"Is continuously experimenting to drive",
		"Initiates and executes creative ideas such as",
		"Seeks new ideas and approaches in",
		"Empowers others with the authority and resources to achieve results in",
		"Helps others gain visibility through",
		"Encourages others to solve their own problems in",
		"Delegates to match personal strengths in",
		"Delegates with clearly defined responsibility and authority in",
		"Develops continuous improvement methods in",
		"Conceives of totally new strategies in",
		"Continues to grow and improve in",
		"Devises improved means of accomplishing results in",
		"Is continuously planning for improvement in",
		"Develops innovative strategies such as",
		"Is very innovative under adverse conditions such as",
		"Seeks innovative solutions in",
		"Fosters a curiosity for innovative possibilities",
		"Promotes innovation by",
		"Recognizes the needs of others and reaches out to lend a helping hand in",
		"Establishes effective working relationships in",
		"Generates synergy in",
		"Builds on mutual dependence and understanding in",
		"Promotes the organisation's culture among peers in",
		"Displays an ability to learn rapidly and adapt quickly to changing situations in",
		"Shares learning experiences with peers in",
		"Promotes a learning culture of",
		"Committed to continuously learning in",
		"Responds quickly to new instructions, situations, methods, and procedures in",
		"Provides team with support in",
		"Collaborates with individual team members to establish a development path in",
		"Holds others accountable for their own results in",
		"Provides team with the resources needed to attain results in",
		"Provides support during periods of organizational change whilst delivering",
		"Develops workable action plans in",
		"Creates flexible plans to meet changing opportunities in",
		"Effectively puts plans into action in",
		"Excels in developing strategic alternatives in",
		"Formulates strategies, tactics, and action plans to drive results in",
		"Is capable of distinguished performance in a higher-level position leading",
		"Has reached the level for promotional consideration in",
		"Can handle bigger projects and assignments in",
		"Is making strong efforts to acquire greater experience and skills to increase potential for advancement in",
		"Is enhancing growth potential through additional education and training in",
		"Displays a practical approach to solving problems in",
		"Develops creative solutions in",
		"Turns problems into opportunities in",
		"Effectively solves problems rather than symptoms in",
		"Is skilled in proposing optional solutions in",
		"Is an important contributor to the successes of the department delivering",
		"Makes a substantial contribution to the continued operation and growth of the organisation in",
		"Sets realistic timetables to keep projects on target whilst delivering",
		"Is transparent with a project's progress in",
		"Makes effective use of all available resources when given a project in",
		"Clearly establishes project goals and objectives in",
		"Gives consistent recognition to others working in",
		"Maintains a work situation which stimulates the growth of individuals in",
		"Makes certain that others have a clear understanding of their responsibilities to deliver",
		"Is readily available for support to others in",
		"Recognizes and deals with signs of burnout in colleagues working in",
		"Consistently meets all deadlines in",
		"Prepares meeting agendas that are concise and time-saving in",
		"Keeps meetings on schedule when discussing",
		"Respects the time of others working on",
		"Makes effective use of discretionary time in",
		"Excels in living the organisation's values in",
		"Promotes strong support of our mission and vision in",
		"Is able to turn visions into actual action plans in",
		"Demonstrates an ability to transfer vision into execution in",
		"Excels in contributing to our goals in",
		"Takes the initiative and is proactive in gathering information, assembling the tools or team members required to complete a project on time and to budget in",
		"Sets measurable goals for themselves and the team and regularly monitors performance in",
		"Provides strong evidence of achieving specific tasks or accomplishments in",
		"Has not matched the performance of colleagues in relation the productivity goal of",
		"Has fallen below the productivity target set in last year's performance review in",
		"Works effectively within a team environment to achieve specific tasks or projects such as",
		"Develops constructive working relationships with internal and external stakeholders in the field of",
		"Is an effective team player as demonstrated by their willingness to help out and contribute as required in",
		"Is proactive in sharing knowledge, skills and expertise with other team members in",
		"Could demonstrate more of a team focus by helping others achieve tasks to complete the overall project in",
		"Displays a tendency not to contribute in team or project meetings and doesn't always participate in team activities or bonding exercises in",
		"Is always punctual and is respectful of colleagues by arriving on time for meetings about",
		"Shows a willingness to go the extra mile during peak periods of work delivering",
		"Has not met the required standards of punctuality and attendance in meetings on",
		"Displays the ability to communicate at all levels – up, down and across the business in",
		"Excels in developing lines of communication with external clients and stakeholders in",
		"Regularly contributes ideas and insights to team and project meetings in",
		"Needs to work on their written communication skills in",
		"Room for development of listening skills particularly in team meetings when different viewpoints are being expressed when working on",
		"Needs to display a greater willingness to participate in team and project meetings by contributing more ideas and insights in",
		"Is able to effectively collaborate with team and project members in order to complete a task in",
		"Shows a willingness to share ideas, best practice techniques and new ways of doing things in",
		"Is a team player and has a cooperative and harmonious disposition in the delivery of",
		"Has a tendency to work in isolation on",
		"Can be overly negative or critical in making contributions to team or project meetings about",
		"Fails to see the bigger picture beyond the team and department in",
		"Consistently delivers beyond expectations in all areas of",
		"Makes an outstanding contribution to the team's productivity levels in",
		"Has not met the required productivity standards set for the project function in",
		"Is inconsistent in meeting the productivity targets set at the performance appraisal and review checkpoints in",
		"Regularly meets all required team and project deadlines in",
		"Always comes prepared for meetings with an agenda and supporting papers about",
		"Takes the time to digest the information and comes to meetings ready to make contributions to",
		"Effectively chairs meetings so that everyone is encouraged to make a contribution in",
		"Their agendas are kept on schedule and a clear record of outcomes and actions is circulated on time about",
		"Has improved our administration by implementing improvements to the flow of",
		"Has devised better ways to achieve administrative functions that deliver",
		"Avoids duplicate information when coordinating the administration of",
		"Needs to improve time management abilities so that projects and tasks are consistently delivered on time and if not, then the reasons why are effectively communicated at the earliest opportunity when it involves",
		"More attention could be paid to time management of meetings and meeting preparedness for",
		"Could contribute more by looking for innovations and improved ways of carrying out administrative support functions in",
		"Understands the individual strengths of team members and is an effective motivator for",
		"Effectively delegates tasks to other team members with clear responsibilities and expectations in",
		"Displays a strong work ethic and sets an excellent example to others involved in",
		"Promotes a positive team environment that is reflective of the organisation's culture and values towards",
		"Is willing to offer support and guidance to employees working in",
		"Convinces business leaders of the strategic value in",
		"Builds for the future whilst minimizing risk with"
	],
	"appraise_quant": ["Improved production of",
		"Exceeded the original goal of",
		"Elevated the team's success with",
		"Generated gains in",
		"Exceeds normal output standards in",
		"Continuously produces more than expected in",
		"Consistently exceeds performance goals in",
		"Beats targets in",
		"Delivers more personal impact than others in",
		"Improved overall productivity levels in",
		"Achieved or exceeded the goal set in last year's performance review in",
		"Has an excellent attendance record for the year improving in",
		"Increased their sick leave and absence from work in",
		"Regularly exceeds the productivity targets set at each appraisal and review checkpoint in",
		"Exceeds our productivity expectations for the job role / project function in",
		"Exceeds expectations in",
		"Underachieves on agreed deliverables in",
		"Jumpstarts digitial initiatives in"
	]
};

export default dialectData;